// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Psytest.ServiceMain.Infrastructure;

#nullable disable

namespace Psytest.ServiceMain.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20250928200359_CreatePbqTest")]
    partial class CreatePbqTest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Psytest.ServiceMain.Domain.Entities.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d22530e2-9c20-4365-9265-4bb6c9b8e8c5"),
                            Description = "Психологический тест, разработанный Максом Люшером, основан на идее о том, что цветовые предпочтения могут раскрыть эмоциональное состояние и черты характера человека.",
                            Name = "Тест Люшера",
                            ShortDescription = "Психологический цветовой тест Макса Люшера"
                        },
                        new
                        {
                            Id = new Guid("f49ef84b-8d71-4d0e-94ee-24e09fbeeca0"),
                            Description = "Психологический тест, разработанный для оценки поведенческих качеств человека, основан на анализе типичных моделей поведения в различных ситуациях. Тест помогает выявить личностные особенности и адаптивность к окружающей среде.",
                            Name = "Тест PBQ",
                            ShortDescription = "Психологический тест поведенческих качеств (PBQ)"
                        });
                });

            modelBuilder.Entity("Psytest.ServiceMain.Domain.Entities.TestAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("RawAnswers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("TestAnswers");
                });

            modelBuilder.Entity("Psytest.ServiceMain.Domain.Entities.TestResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ReportPath")
                        .HasColumnType("text");

                    b.Property<string>("ResultText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("Psytest.ServiceMain.Domain.Entities.TestSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("TestSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
